### ISSUE TITLE
Create place for COVID-19 DREAM Challenge

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#1]
Expecting to launch website week of 4/20/2020; not open to public yet. Same framework as EHR Mortality DREAM Challenge.

**Comment by monicacecilia** [comment]
Pinging @alexisgraves. :bowtie:

**Comment by amvolz** [comment]
**_New content provided today:_**
![EHR COVID DREAM Challenge](https://user-images.githubusercontent.com/59209633/80770525-60010b80-8b05-11ea-8a94-7d10a8e1a525.png)

REGISTRATION IS NOW OPEN! 
The rapid rise of COVID-19 has challenged healthcare globally. The underlying risks and outcomes of infection are still incompletely characterized even as the world surpasses 1 million infections. Due to the importance and emergent need for better understanding of the condition and the development of patient-specific clinical risk scores and early warning tools, CD2H has developed a platform to support analytic and machine learning hypotheses on clinical data, without data sharing, to rapidly discover and implement approaches for care. CD2H and the University of Washington (UW) School of Medicine previously applied this approach in the successful EHR DREAM Challenge focusing on Patient Mortality Prediction. 

CD2H is asking the following challenge question: Of patients who have at least one clinical encounter/visit at UW Medicine and who were tested for COVID-19, can we predict who tested positive? In addition to the initial challenge question, CD2H has identified 9 total questions of interest, 4 of which will be adapted if the first Challenge is successful.

The EHR COVID-19 DREAM challenge is made possible by funding from the National Center for Advancing Translational Sciences (NCATS) and partnerships with the University of Washington School of Medicine Departments (Anesthesiology and Pain Medicine, Radiology and Biomedical Informatics and Medical Education), UW Medicine Information Technology Services, the Institute of Translational Health Sciences, the Center for Data to Health, and the CLEAR Center.

Register: https://www.synapse.org/#!Synapse:syn21849255/wiki/601865

**Comment by alexisgraves** [comment]
The COVID-19 EHR DREAM Challenge information is now up on the website [here](https://covid.cd2h.org/EHR_DREAM_COVID-19). It is also linked on the main menu under "Resources".

**Comment by monicacecilia** [comment]
:bowtie:
