### ISSUE TITLE
Create project workflow and data governance diagrams

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#10]

**Comment by monicacecilia** [comment]
@mellybelly - where can we find information about architecture layout so @richalorimor can start looking into this ASAP.

**Comment by monicacecilia** [comment]
@richalorimor 
- I am assuming 'architecture diagrams' here to mean project workflow' and 'data governance.'
- The more I think about it, there more I realize that slides 7 & 11 in the AMIA deck are the ones we can use as the best starting points to inform with these details about the project (as we discussed yesterday). Adding here for thoroughness. 
- @mellybelly - please stop us if we're not on the right track. :bowtie: 

![Screen Shot 2020-04-30 at 10 55 26 AM](https://user-images.githubusercontent.com/1714621/80743767-6aee7880-8ad2-11ea-971d-029320bc358f.png)

![Screen Shot 2020-04-30 at 10 55 37 AM](https://user-images.githubusercontent.com/1714621/80743783-7346b380-8ad2-11ea-9689-a9166bb5e9ec.png)

**Comment by richalorimor** [comment]
@monicacecilia Thank you Moni... Do you know what these are built in? You mentioned Illustrator, wondering if you have those original files?

**Comment by richalorimor** [comment]
If not I can re-build fairly quickly.

**Comment by monicacecilia** [comment]
Hi @richalorimor - Unfortunately, no AI files for these two images, only for the ones explaining FHIR (towards the end of the same talk). These two were created using Google Slides, and the original images are in the [N3C deck for AMIA](https://docs.google.com/presentation/d/1-g1yf0DT1ImqHe5eFpkhUvUJiDLE5_vtzdxMTVywlHA/edit#) referenced above.

**Comment by mellybelly** [comment]
@jaeddy @jguinney

**Comment by mellybelly** [comment]
Everyone please coordinate. I don't know who is doing these and it is now quite urgent.

**Comment by richalorimor** [comment]
@mellybelly Good morning Melissa, 
I will move these to my top priority - my plan is to clean them up and make them consistent with design and goals of the overall site that we are putting together. I want to make sure that is what you are looking for in these slides or if there are any additions?

**Comment by richalorimor** [comment]
Hello Melissa and Anita,
I've attached round 1 of the first slide (working on slide #2 shortly). I thought that I would see what you think so far - the second slide will come together quickly once the direction is OK'd. As you can see, I've consolidated a bit, and re-worded slightly to make the process more linear, hopefully more explanatory at-a-glance (through my filter)
[Architecture_Diagrams.pdf](https://github.com/National-COVID-Cohort-Collaborative/covid.cd2h.org/files/4602456/Architecture_Diagrams.pdf)
 and N3C-branded. I understand that that may be out of the scope of my purview, so no worries if you need to go back to the original verbiage. 

Please lmk what you think, and have a great weekend. (I will be online and working all weekend, so don't hesitate to reach out over the weekend if you would like). Rich
@mellybelly

**Comment by mellybelly** [comment]
@jaeddy do you want to share w @richalorimor your ideas for architecture? I will also upload here the data harmonization workflow
