### ISSUE TITLE
Post documents from partnership packet

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#11]
Add documents from the Hub Partnership packet: DTA, DUA, Phenotype, NOSI, etc.

**Comment by monicacecilia** [comment]
Pinging @alexisgraves. :bowtie:

**Comment by monicacecilia** [comment]
@amvolz 
- Please to give @alexisgraves the location of these documents. 
- Also, are we still allowed to publicize the DUA & DTA files?

**Comment by monicacecilia** [comment]
Moved the bits about 'how to join' to a new ticket --> #18

**Comment by amvolz** [comment]
Checking with leadership. Will advise.

**Comment by amvolz** [comment]
Slide on wireframe/storyboard has been made listing documents in the welcome packet. Not all seem to be finalized and still contain comments. A new 1-page brochure is being created. We need to find a way to link them publicly, as they all reside in the N3C google drive now. We still do not have NCATS permission to publish DUA & DTA.

**Comment by amvolz** [comment]
The DTA is now posted with the NIH-NCATS-N3C resources on their website, so we are not waiting to add it to our site. The DUA is still being finalized; if it will be also be posted on the NCATS-N3C page, then we can close this ticket. 

@waldenan can you confirm if the final DUA document will be housed on NCATS-N3C site, or if we should keep this ticket open to add to our Partner Packet? Thank you!

**Comment by waldenan** [comment]
We are not sure but I am assuming it will be handled similarly to the DTA
and housed at NIH
Anita Walden

**Comment by amvolz** [comment]
Update: DUA should be finalized by week of June 8th. Final DUA will be housed on the NIH/NCATS N3C webpage. (It will not go in the Partnership Packet on the N3C site.)
