### ISSUE TITLE
Create webinar archive to house recorded presentations

### ISSUE THREAD

**Issue by monicacecilia** [National-COVID-Cohort-Collaborative/covid.cd2h.org#12]
**Request from @amvolz.**

We would like to have:
- [ ] An archived library of all webinars
- [ ] A link to this collection of webinars from the 'Curated Resources' top level menu

**Comment by monicacecilia** [comment]
(apologies for the fast 'comment' trigger. I updated the request in the initial comment. see above.) :bowtie:

**Comment by monicacecilia** [comment]
@eichmann - I'd assign Alexis, but she hasn't joined the org yet. Adding you to bring to the attention of the _Dashboard & Portal_ team. Thank you! :bowtie:

**Comment by monicacecilia** [comment]
Also, bringing to the attention of @alexisgraves. :bowtie:

**Comment by amvolz** [comment]
Per Melissa, only post webinar presentations (AMIA, NCATS, etc.) We will not be posting the workstream recorded meeting webinars. A new slide on the wireframe/storyboard has been created to show menu and page layout.

**Comment by monicacecilia** [comment]
Work has been completed.
@alexisgraves please update when you publish the page so we can close. 
Thank you!! 🌺

**Comment by alexisgraves** [comment]
@monicacecilia Thank you! The webinar page is now [live](https://covid.cd2h.org/webinars) and listed under the "About" menu as "N3C Webinars". :)
