### ISSUE TITLE
Update 'About' page

### ISSUE THREAD

**Issue by monicacecilia** [National-COVID-Cohort-Collaborative/covid.cd2h.org#16]
Under recommendation of @amvolz - 
---------------------
In the ['About' page](https://covid.cd2h.org/about), please: 
- Remove text and logos referring to HHS
  - [x] Remove text about HHS
  - [x] Remove logo for FDA. Get input from @mellybelly on wheteher or not this can be added back.
  - [x] Remove logos for VA, CDC, and DoD
- [x] Update abbrev. "ICs" to "_Institutes and Centers_"

**Comment by alexisgraves** [comment]
All logos and text associated with HHS have been removed from the new partnership image.

**Comment by monicacecilia** [comment]
@mellybelly - this ticket needs your input. Are we allowed to show the FDA logo or not?

**Comment by monicacecilia** [comment]
@alexisgraves - @mellybelly recommended that we ask Ken Gersing.

**Comment by deacyma** [comment]
@monicacecilia I have updated the ticket:

- Remove text and logos referring to HHS   - please remove
-  Remove text about HHS   - please remove 
-  Remove logo for FDA. Get input from @mellybelly on wheteher or not this can be added back.   - please remove 
-  Remove logos for VA, CDC, and DoD  - please remove 
-  Update abbrev. "ICs" to "Institutes and Centers"  - yes [‎4/‎30/‎2020 2:31 PM]

**Comment by monicacecilia** [comment]
@alexisgraves: we have updates! 🎉  The one thing left to do is to update the acronym _"IC"_ to _"Institutes and Centers"_.

Updated screenshot below, in case it's useful. 

![Screen Shot 2020-04-30 at 11 39 48 AM](https://user-images.githubusercontent.com/1714621/80746886-6c6e6f80-8ad7-11ea-8ff7-efb0e99e5ee3.png)

**Comment by alexisgraves** [comment]
@monicacecilia Yay, thank you! Here is the updated graphic with the changes mentioned and a couple of layout tweaks. It is also on the website [here](https://covid.cd2h.org/about). 
<img width="1666" alt="agency_partners" src="https://user-images.githubusercontent.com/12225601/80748419-81a0c980-8aea-11ea-9e3f-bc36c28602de.png">

**Comment by monicacecilia** [comment]
Brilliant! :bowtie:
