### ISSUE TITLE
Update 'Meet the Team' page

### ISSUE THREAD

**Issue by monicacecilia** [National-COVID-Cohort-Collaborative/covid.cd2h.org#17]
- There needs to be added clarity about who should be represented in the ['Team' page](https://covid.cd2h.org/team). 
  - Is there a formal SOP for figuring out who to add? 
  - Do we just use Justin's list of WS leads and subgroup leads? 
  - Anyone else?

**Comment by monicacecilia** [comment]
Would also like input from Anita and Usman, but they are not in the GH org yet.

**Comment by amvolz** [comment]
@alexisgraves We should only show workstream leads under a "Workstream Leadership" section (change title and see weekly bulletin for names). Change "Communications Management" to "N3C Administration" and also list project managers (can get from [spreadsheet](https://docs.google.com/spreadsheets/d/1BimUSQsy4jlGZlD2DavDlIcZbHL-p4dkbQxhnTnywLc/edit#gid=753430784)). 

Then we can have another place to give attribution to all the many contributors, as this is a different function.

**Comment by amvolz** [comment]
Suggested Categories for the N3C Team:
N3C Project Leadership
N3C Workstream Leadership
N3C Administration

Can use avatar if no head shot available. Proved name, credentials and organization under the photo/avatar.

**Comment by amvolz** [comment]
Take to N3C Leadership meeting

**Comment by amvolz** [comment]
Updates made to storyboard with Anita. Can start putting up with headshots that we have and avatars for those we are waiting for. New main menu title is WHO WE ARE. Waiting for confirmation on the the NLP subgroup leads.

**Comment by amvolz** [comment]
Done!
