### ISSUE TITLE
Add information about how to join the N3C effort

### ISSUE THREAD

**Issue by monicacecilia** [National-COVID-Cohort-Collaborative/covid.cd2h.org#18]
We would like to include information about how to join the N3C effort. Currently we have this document --> bit.ly/n3c-join-instructions. Could we please turn this into a page on the N3C website, or add it to an existent, appropriate page?

Thank you! 🌺

**Comment by alexisgraves** [comment]
@monicacecilia We actually have a lot of this information currently on each of the individual workstream pages (ex. [Governance](https://covid.cd2h.org/N3C_governance), [phenotype](https://covid.cd2h.org/N3C_phenotype), [harmonization](https://covid.cd2h.org/N3C_harmonization), and [analytics](https://covid.cd2h.org/N3C_analytics)). Can we add the additional information/links from that document here and possibly readjust when we update the landing page?

**Comment by monicacecilia** [comment]
Yep, brilliant. For now, we could add GH links for the WSs that have them, a link to the survey for the Phenotype WS, etc. The things that are not already there. 
And then we punt it for updates to landing page. 
Thanks @alexisgraves!

**Comment by amvolz** [comment]
This would be the Partnership Welcome Packet. Melissa wants this all together on N3C landing page. We can start populating with the documents we know are finalized (N3C Site Survey, NOSI, CDM Data Dictionary, CTSA Hub Template, etc.) Need to check on when we can upload DUA and DTA.

**Comment by monicacecilia** [comment]
DUA and DTA is now out of scope. 
All other work is completed. Closing. :bowtie:
