### ISSUE TITLE
New workstream for synthetic data

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#19]
We need a new page on the website for this new workstream. 
@prpayne5 is the lead and can provide text. @alexisgraves can you come up with an icon?

**Comment by alexisgraves** [comment]
@mellybelly How about something like these? Please let me know if I'm going in the right direction or if you want any changes! If you like the one with the DBs and the lock I can try to simplify it a bit if it is too busy. Thanks! :) 


Option 1: W/O DB            |  Option 2: With DB
:-------------------------:|:-------------------------:
 ![synthetic_data_small](https://user-images.githubusercontent.com/12225601/81424879-3acf5700-911c-11ea-83d6-fe186fdd372f.png)  | ![synthetic_data_w_db_small](https://user-images.githubusercontent.com/12225601/81428122-6f91dd00-9121-11ea-85f5-65e8dd401371.png)

**Comment by prpayne5** [comment]
I think something along the lines of option 2 makes more sense - I feel
like option 1 infers more of a data "sub selection" process ...

Thanks for the quick response on this!

Philip

**Comment by eichmann** [comment]
@prpayne5 - I also suggested to @alexisgraves something along a transmogrifier line (ala Calvin and Hobbes).

**Comment by alexisgraves** [comment]
Based off of @eichmann's idea, maybe something more along the lines of option 3? It is rough, but I can work on it some more if we like the direction.  Please feel free to brainstorm or point me in other directions! :) Thanks!


Option 2: With DB            |  Option 3: Transmogrifier
:-------------------------:|:-------------------------:
![synthetic_data_w_db_small](https://user-images.githubusercontent.com/12225601/81440034-04ea9c80-9135-11ea-9d3b-7c2485d914cf.png) |  ![synthetic_data_process_small](https://user-images.githubusercontent.com/12225601/81440065-0ddb6e00-9135-11ea-84f1-5ad89cdf6380.png)

**Comment by richalorimor** [comment]
@andrewjneumann @prpayne5 Hello Andrew and Phillip, wanted to ping you both for a final sign-off on the logo that Alexis built for the SYNTHETIC DATA Workstream. We are going to incorporate it on the HP that will go live tomorrow. Thank you!

Thank you
Rich
![SYNTHETIC_DATA_WORKSTREAM](https://user-images.githubusercontent.com/64401815/81990391-f1877780-95f3-11ea-8143-0e8cdf0667f2.png)

**Comment by andrewjneumann** [comment]
> @andrewjneumann @prpayne5 Hello Andrew and Phillip, wanted to ping you both for a final sign-off on the logo that Alexis built for the SYNTHETIC DATA Workstream. We are going to incorporate it on the HP that will go live tomorrow. Thank you!
> 
> Thank you
> Rich
> ![SYNTHETIC_DATA_WORKSTREAM](https://user-images.githubusercontent.com/64401815/81990391-f1877780-95f3-11ea-8143-0e8cdf0667f2.png)

Looks great to me! I'll differ to @prpayne5 for the approval :-)

**Comment by mellybelly** [comment]
I love it!

**Comment by prpayne5** [comment]
Agreed ++

P
