### ISSUE TITLE
Implement Zenodo

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#2]
Kristi Holmes will provide input.

**Comment by amikaili** [comment]
This is Work in progress.  Please see google doc for status:

https://docs.google.com/document/d/1I43rfm-Z5GAKhuB1dQtZ4PJnxA7PkUR2-b9oGi5p6UE/edit#

- arman

**Comment by amikaili** [comment]
Installing Invenio FULL STACK localhost instance (Postgres database, search indexes, queues and caches)
Got as far as I could with just a client for OAI Harvesting (staged default format XML metadata)
FULL STACK Invenio will have Elastic Search and capability to stage JSON metadata https://github.com/inveniosoftware/training

**Comment by monicacecilia** [comment]
From the google doc referenced above:
> Note - Zenodo has been deprecated!
> XML based metadata schema Zenodo supported are now deprecated (DataCite…)
> Newer Invenio now supports latest XML based metadata (eg. Dublin Core); as well as cross-format (transformation/conversion) support for JSON (enabling Elastic Search…).  

@amikaili @amvolz - does this mean this has been updated and we can close? 
Else, is there an action item to follow up with?

**Comment by amikaili** [comment]
Concur (can close)

**Comment by monicacecilia** [comment]
:bowtie:
