### ISSUE TITLE
Enumerate and specify dashboards

### ISSUE THREAD

**Issue by jaeddy** [National-COVID-Cohort-Collaborative/covid.cd2h.org#20]
cc @eichmann, @wakibbe, @mellybelly, @waldenan, @amvolz 

Thinking about this in the context of overall architecture for N3C, I'm trying to scope out the landscape of various dashboards that we might need to support. Some questions that we'd want to answer for each (might be worth linking out to a Google Doc to actually fill in the answers...):

- What information needs to be presented?
- Where will the data be sourced?
- Who is the target audience?
- Where will the UI sit (and where will it be hosted)?
- Who will have access to view?
- What are the security/auth requirements?
- Who will be responsible for maintaining?
- What existing apps/tools can be used?

**Note:** I'm not intending to get into the details of _design_ for each dashboard at this point.

---
 
**Administrative**
- Governance/onboarding status
- Data ingest workflow status/QC

**Content**
- Data summaries/metrics (limited, synthetic)
- Derived/subsetted datasets
- Tools & resources
- Benchmarking metrics, usage/analytics
- Clinical scenarios
- Insights, reports

**Meta**
- Meetings*
- Materials** (video recordings, notes/minutes, presentations)

\* We mentioned this somewhat jokingly, but there would be value for our community of users/to quickly understand (i) what meetings are happening and when; (ii) what topics are being discussed; (iii) what the target phenotype is for participants; etc.

\** The current website might be sufficient for this.

---

What did I miss?

**Comment by amvolz** [comment]
**Literature** (including pre-prints)

**Comment by amvolz** [comment]
**Attribution**

**Comment by amvolz** [comment]
A [Dashboard Spreadsheet](https://docs.google.com/spreadsheets/d/1LQNlAOcVqCeu3Sz1_y2UUCbCRlCGQcne8LCl2ThEPQ8/edit#gid=0) has been compiled.

**Comment by amvolz** [comment]
This is part of the Portals & Dashboard Subgroup workflow, which they are managing separately.
