### ISSUE TITLE
Add NCATS funding language to footer of N3C website

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#22]
The CTSA Program National Center for Data to Health (CD2H) is supported by the National Center for Advancing Translational Sciences (NCATS) at the National Institutes of Health (Grant U24TR002306).

If you have problems viewing PDF files, download the latest version of Adobe Reader
For language access assistance, contact the NCATS Public Information Officer

National Center for Advancing Translational Sciences (NCATS), 6701 Democracy Boulevard, Bethesda MD 20892-4874 • 301-594-8966

**Comment by richalorimor** [comment]
Added to site architecture. Will close the ticket as soon as Alexis @alexisgraves has the copy incorporated to the live site.

**Comment by alexisgraves** [comment]
Per group discussion: We should run this wording by NCATS just to be sure they approve :)

**Comment by monicacecilia** [comment]
This is approved language. Please proceed. Thank you @alexisgraves
