### ISSUE TITLE
Welcome Partner Packet Website Text - KEEP THIS ONE

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#23]
The Website team needs the Welcome Package text that will be displayed on the N3C landing page.

**Comment by richalorimor** [comment]
Here is a rough word-count that we could use:

BECOME A VALUED PARTNER of N3C

Be the first to know valuable benefits 
benefits bene fits benefits ben efiben efits 
benefits benefits benefits benbeneefib enefits 
bene fits be nebfits benefits be nefiben efits 
benefits benefits benefits.

**Comment by richalorimor** [comment]
@mellybelly Good morning Melissa, our top priority (other than the HP) today will be populating and linking the WELCOME PARTNER PACKET (subsequent pieces and forms) and ENGAGE pieces. Can you provide (or show me) where/how to get to those. 

I also need:
• Top-level quote for the HP 
• Become a Valued Partner copy (I can write placeholder copy for now if you want me to)
and we will be working on art for subsequent pages in the meantime, in addition to the pages that Alexis already has to start populating

Thanks!

**Comment by mellybelly** [comment]
Draft text (pls edit)

BECOME A VALUED N3C PARTNER 

Whether an institution or an individual, N3C welcomes everyone. Diverse institutional partners ensure that the data within N3C is representative of our nation and can help design the N3C program. Collaborations between clinicians, translational researchers, informaticians, and data scientists are needed to address the most pressing COVID-19 clinical questions. Rapidly share collaborative results and get attribution for your contributions. Change science and save lives, now. Join us.

**Comment by waldenan** [comment]
Let's add this to the end of the text...._The packet contains important information on how to get started and information such as the protocol and key contacts._


Once that has been added it is ready to place on the Website when the welcome is ready

**Comment by amvolz** [comment]
@mellybelly @waldenan 

I have edited the partner packet text and if you approve, it is ready for website.

**BECOME A VALUED N3C PARTNER**
Whether you are a member of an organization or an individual, N3C welcomes your collaboration. Diverse institutional partners ensure that the data within N3C are representative of our nation and can help design the N3C program. Collaborations among clinicians, translational researchers, informaticians, and data scientists are needed to address the most pressing COVID-19 clinical questions. N3C provides a pathway to rapidly share collaborative results and get attribution for your contributions. Be a part of the evolution of science and save lives, now. Join us!

The Welcome Partner Packet contains important information on how to get started, such as the N3C protocol, governance documents and key contacts.

**Comment by mellybelly** [comment]
Minor edits:

BECOME A VALUED N3C PARTNER
Whether you are a member of an organization or an individual, N3C welcomes your collaboration. Diverse institutional partners ensure that the data within N3C are representative of our nation and can help design the N3C program. Collaborations among clinicians, translational researchers, informaticians, and data scientists are needed to address the most pressing COVID-19 clinical questions. N3C provides a pathway to rapidly share collaborative results and get attribution for your contributions. Help make science go faster and save lives. Join us!

The Welcome Partner Packet contains important information on how to get started, such as the N3C protocol, governance documents, and key contacts.

**Comment by amvolz** [comment]
@mellybelly OK good. Is it ready to give to web team? Or do we have to pass by NCATS?

**Comment by mellybelly** [comment]
I don't think it requires approval, nothing controversial or sensitive in there.

**Comment by amvolz** [comment]
Approved by Melissa and send to web team for upload on site. This ticket along with #21 and #28 will be closing.

**Comment by amvolz** [comment]
Completed today 5/15/2020
