### ISSUE TITLE
Create/Update Architecture Diagrams for Workstream Pages

### ISSUE THREAD

**Issue by monicacecilia** [National-COVID-Cohort-Collaborative/covid.cd2h.org#25]
@mellybelly requests that we:

### 1. Create / update diagram for Data Ingestion and Harmonization Workflow for the N3C website
![Screen Shot 2020-05-13 at 4 10 23 PM](https://user-images.githubusercontent.com/1714621/81875063-4663b900-9534-11ea-9c66-480b71520946.png)

-------------------------

### 2. Create / update diagram for N3C Collaborative Analytics Platform (CAP) Architecture for the N3C website
![Screen Shot 2020-05-13 at 4 11 03 PM](https://user-images.githubusercontent.com/1714621/81875103-60050080-9534-11ea-806d-2d4547811540.png)

**Comment by jmcmurry** [comment]
These are a great start; where are the vectors?

**Comment by monicacecilia** [comment]
No vectors available, afaik. 😭

**Comment by amvolz** [comment]
Rich is working on architecture diagrams. Andrea put recent slide deck diagrams for each workstream on the storyboard to inspire artwork for each.

**Comment by amvolz** [comment]
Rich will hand off the "shell" he designed to Alexis and Will this week. Andrea will send drafted storyboard slides to PMs to have leads comment on artwork/diagrams they would like to have on their pages.

**Comment by amvolz** [comment]
It looks like Rich's architecture was not able to be applied? 
Workstreams agreed to artwork on their respective storyboard slides. Can we use these to populate their webpages?

**Comment by amvolz** [comment]
UPDATE TO THIS ISSUE: Previous Architecture diagrams created by Rich Lorimor, as well as the diagrams placed on storyboard slides, have become outdated with the progression of the Enclave being live. This architecture diagram issue has been put on hold until more pressing web pages can be created and made live for active use of the Enclave. 

Once those issues are taken care of, this issue will be revisited with the latest and most current diagrams taken from slide deck presentations and/or web team development. Stay tuned.

**Comment by amvolz** [comment]
Workstreams and groups are being revised December 2020. Complete change of workgroup naming and layout coming soon.
