### ISSUE TITLE
Hub packet website text - Due May 14th

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#28]
Starter Welcome Packet website text is here. Melissa you review it and send to the Website group to be posted with the hub packet.

[Clinical Institutions Welcome Packet text ](https://docs.google.com/document/d/17NWSbDyIlCErtf5lzhcsF3cZhIgJ8LF2RJHgzjzkeiQ/edit)

_The Welcome Packet is for clinical institutions who want to participate in the N3C effort. The packet contains important information on how to get started and information such as the protocol and key contacts._

resending it because the website group said they didn't see it.

**Comment by monicacecilia** [comment]
- @waldenan - what is the action item here? Going by the phrase: _"Melissa you review it and send to the Website group to be posted with the hub packet,"_ it sounds like @mellybelly still needs to review the text. Is this correct?
- @alexisgraves @richalorimor - bringing to your attention as @waldenan mentions 'the website group' in this ticket. Please do not post until we hear confirmation from @waldenan or @mellybelly 

Thank you! :bowtie:

**Comment by amvolz** [comment]
I'm confused by an assignment I got this morning for this ticket. As Moni mentioned above, it is unclear what the action is. The packet appears to be still pending approval? I understand that Andrew Neumann is putting the approved docs into a PDF binder. This approved binder will then be given to Alexis and Rich to put in the designated place on the new covid website.

**Comment by amvolz** [comment]
There are 3 tickets for this same action. I started the original #21 on Tues 5/12 per instruction. Anita created a similar ticket #23 on Weds 5/13 and another #28 today Thurs 5/14. It looks like ticket #23 has the language Melissa wrote so I will edit from there. I motion to keep ticket #23 and delete the others, or merge if possible to alleviate confusion.

**Comment by amvolz** [comment]
See ticket #23 for final resolution. Closing this ticket.
