### ISSUE TITLE
Synthetic Workstream Initial Meeting time Please post(may change weekly)

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#29]
Synthetic Workstream initial meeting is scheduled for tomorrow 5/21 at 10:30am PT/12:30pm CT...Can we post on the Website. Please check with Andrew to review information. 

Thanks!

**Comment by alexisgraves** [comment]
Looks like @amvolz has the meeting on the N3C calendar (so it is also showing on the site events)! For more visibility we can also add a tile (something like the image below) to the carousel and link it to the event page on the site [here](https://covid.cd2h.org/calendar/event/180). Which I can remove tomorrow after the meeting. @andrewjneumann Let me know if you approve. Thank you! :) 
![synthetic_data_meeting](https://user-images.githubusercontent.com/12225601/82506425-5f84e080-9ac5-11ea-918c-b0c069b446e9.png)

**Comment by andrewjneumann** [comment]
@alexisgraves looks good. Thank you! The next two meetings are scheduled:

Next meetings: 5/26 2:30pm PT/4:30pm CT
6/1 12pm PT/2pm CT

**Comment by alexisgraves** [comment]
Great! The carousel tile is now up on the [main site](https://covid.cd2h.org/)! :)
