### ISSUE TITLE
Remove row with government agencies on the About page

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#30]
Remove row
<img width="625" alt="Gov agencies row" src="https://user-images.githubusercontent.com/59209633/82617672-9e7a6b00-9b85-11ea-8763-4be2e55b9161.PNG">

**Comment by amvolz** [comment]
@alexisgraves Please remove these as "Agency Partners". Thanks!

**Comment by alexisgraves** [comment]
That row is now removed from the static partner graphic [here](https://covid.cd2h.org/about). :)

**Comment by amvolz** [comment]
Thank you @alexisgraves!
