### ISSUE TITLE
Announcements- Section Edited by Andrea Needed

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#32]
I think we may need an Announcements/News section on the Landing page that Andrea can use to quickly post information. New information is coming out every couple of days or more and the Admin team should not have to bother the programmers for this.

Maybe the 2nd Rectangle can be divided to allow for this. It is not urgent but would you consider it during your design phase.   Let's review some approaches during the Wed Web Call.

**Comment by amvolz** [comment]
Added to 5/27/2020 meeting agenda.

**Comment by amvolz** [comment]
Status pending. Added to 6/3 and 6/10 meeting agendas.

**Comment by amvolz** [comment]
Done.
