### ISSUE TITLE
Engagement with N3C - Clickable - Target Wed AM?

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#33]
Hi, the Engage with N3C doesn't look like a place where people can click to find more information Can this be updated to look clickable or/and add text to say "click here to"-"gain access to N3C documents/meeting invites"

**Comment by amvolz** [comment]
@alexis or @richalorimor, per Anita's comment above, I agree that the circle that says "Engage with N3C" doesn't look like a live link. I used the text editor and edited the text to say "Click here to engage with N3C!" However, after I saved my changes, it does not reflect them on the front page. Do I not  have permission to edit this block? Let me know how to fix. Thanks!

**Comment by richalorimor** [comment]
Alexis, attached is an updated kicker for you with LEARN MORE added to it.
![engage_copy](https://user-images.githubusercontent.com/64401815/82864135-bbda6c80-9ed8-11ea-846d-a8fb1c2446f2.png)

**Comment by waldenan** [comment]
Yes, That works!


Anita Walden

**Comment by alexisgraves** [comment]
The new graphic is now live on the site! :)

**Comment by amvolz** [comment]
I don't think "Learn More" really conveys that that is the place to join. I would say "Join Here" or "Onboard Here". It's more direct and says what it means. Plus we keep telling people they have to "onboard" so that word is everywhere now.
