### ISSUE TITLE
Add FAQs page

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#36]

**Comment by amvolz** [comment]
Per Anita, each workstream page is to have their own FAQ section, with the 4 subgroup FAQs included on the Collaborative Analytics page. Is this correct? Google docs have been started for each in their respective Google drive folders. Need input from leads on FAQ content.

**Comment by mellybelly** [comment]
the FAQs in the workstream folders were for easy collection during meetings. We need a curated, edited source of truth list for the website to draw upon. I just need to know where to put this list. I am likely to create a .md file in this repo so that the web team can grab them from there?

Moni fine with above suggestion, just wanted each workstream to have an easy place to put them during their meetings.  but this doesn't negate the need for a clean, ready to deploy curated list for the site. this is the droid i am after at present.

**Comment by mellybelly** [comment]
Also we can file this same doc in each workstream's folder, i like that idea moni!

**Comment by amvolz** [comment]
Per Moni's description above, main FAQ document has been created with a TOC. A shortcut was placed in each workstream folder for easy access. Content is currently in process of being compiled. Will ultimately need to be approved by NCATS when ready. (We will need to cross-reference with NCATS' FAQ document so questions are not duplicated.)

In the meantime, web team can work on designing where the FAQ document will go on the N3C website.

**Comment by amvolz** [comment]
At web meeting, discussed that @alexisgraves will create a new content type. FAQ item (when approved) will be added to the ABOUT menu. FAQ document will also be placed on each workstream page.

**Comment by amvolz** [comment]
First version of FAQs was sent to Emily Marti/NCATS Fri June 19 as directed. Approved FAQs will be color coded on the "source of truth" google doc to indicate that they can be put on the website. @alexisgraves is creating place on website to place FAQs once approved by NCATS. Melissa has requested first round of approved FAQs to be posted on the website before Weds 6/24/2020.

**Comment by amvolz** [comment]
Met with NCATS Communications team 6/24/2020. They are still working on the process. Was discussed that it is most important to get NCATS' approval for governance and messaging statements, but perhaps other FAQs could be approved internally by N3C leadership. Another meeting is being scheduled to finalize process. Emily Marti will look at approving some on the list sent to her as soon as she can.

Workaround: In the meantime, I have added a sentence on the home page to make the NCATS FAQs more easily accessible and to be able to answer governance and regulatory questions now.

**Comment by amvolz** [comment]
13 FAQs have been approved by NCATS. New item added under the ABOUT menu: N3C FAQs. More to come from NCATS this week.

**Comment by amvolz** [comment]
13 approved FAQs were moved to RESOURCES menu along with NCATS FAQs so they can be accessed together. (NCATS Communications Team still to approve more on our list which will be added.)

**Comment by amvolz** [comment]
New N3C FAQs going forward will have their own individual GitHub ticket as part of a new process.
