### ISSUE TITLE
start hub-blogs

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#37]
hearing some lovely examples from hubs/regions about their initiatives to garner participation in N3C. It would be terrific to start a blog about these early stories, perhaps even enlist a historian/medical anthropologist.

**Comment by amvolz** [comment]
@mellybelly Need more information for this content. 
Can you forward emails of these stories? 
Or can you provide email addresses of people I can contact to write a blog about their experience?
Also, might be best for you to put out a query for an anthropologist/historian who might be in our N3C already?

**Comment by amvolz** [comment]
Per Melissa on 6/12/2020, there is no current content for this. This can be put in the parking lot until further development. (We are collecting quotes for the weekly Bulletin, so could be a more fully developed byproduct of that effort.)

**Comment by amvolz** [comment]
@alexisgraves Per our discussion, let me know when the new podcast/blog section has been created that would take care of this ticket.

**Comment by amvolz** [comment]
We have the Graticule Novel Cohorts Podcast series (3 episodes so far) under [ABOUT - N3C PRESENTATIONS & WEBINARS](https://covid.cd2h.org/webinars).  We plan to categorize this ever-growing list of recordings and will create a dedicated Podcast section. 

I am going to consider this ticket closed.
