### ISSUE TITLE
N3C Metrics/Statistics on Home Page

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#38]
# of institutions in N3C (sites)
# of collaborators with N3C (people)
What else?

**Comment by amvolz** [comment]
Alexis is working on automation of metrics. Dave has also created a dashboard that pulls from NCATS data for DTA, IRB, etc status. Rich is incorporating to new landing page architecture mock-ups.

**Comment by amvolz** [comment]
Julie is reworking the main spreadsheet that provides some of this data. Will take some time to sort out. Per closed ticket #27, Alexis will only migrate the 2 top horizontal bands for the home page. We will leave the metrics band on hold until the spreadsheet can be coordinated.

**Comment by amvolz** [comment]
Dave wants to wait until spreadsheet is stabilized to begin importing metrics to the home page.

**Comment by amvolz** [comment]
@alexisgraves will change “Live Data Connections” metric to “Sites Depositing Data” .
@alexisgraves will create new metric: “Site Data Available” to match number in the Enclave.

**Comment by eichmann** [comment]
Data element for "Site Data Available" now accessible in the data feed.

**Comment by amvolz** [comment]
New metrics for home page: #Executed DTAs | #Completed Regulatory Requirements | #Sites Depositing Data | #Site Data Available

**Comment by amvolz** [comment]
This has been done on a dev page. @alexisgraves will make it go live.

**Comment by alexisgraves** [comment]
This is now up on the live site :) 
<img width="1430" alt="Screen Shot 2020-10-07 at 2 29 48 PM" src="https://user-images.githubusercontent.com/12225601/95378504-9fe4cf80-08a9-11eb-8a9a-1e29ac024f89.png">

**Comment by amvolz** [comment]
Perfect! Thank you!
