### ISSUE TITLE
Create data egress resource requirements page 

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#39]
This page should give a sense for overall FTE/skills needed for the initial data push and its ongoing maintenance. 

We have had discussions with a few sites and have a start on this document. Where should we put this content @eichmann ?

**Comment by empfff** [comment]
I'm going to write up some material on this for our github wiki, but the text can be repurposed for other N3C websites as well. Will let you know when complete.

**Comment by amvolz** [comment]
@empfff @mellybelly Looking at this ticket from June. I'm not sure what the ask is. Is this still relevant? Is it still in the works? Do we need to bring this to website workgroup @eichmann? Thanks!

**Comment by amvolz** [comment]
@empfff we are closing things down here and converting to Jira. Can I close this issue? Please let me know!

**Comment by empfff** [comment]
Definitely, feel free to close.
