### ISSUE TITLE
Need regulatory processes documentation for CTSA hubs page

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#40]
It would be helpful to have a generic description of the process that organizations will face to provision data to N3C. @empfff  @abwilcox has documented some of this and has a nice diagram, Emily has been helping sites and might know some good ones to enlist to help create such a guide.

**Comment by amvolz** [comment]
This is in the works. Rich has been working on architecture of steps and I have story boarded some information. Will reach out to Emily & Adam.

**Comment by amvolz** [comment]
Emailed Emily, Adam (Lisa, Liz) 6/10/2020 with explanation of issue and attachment of data access slide from Governance meeting
<img width="560" alt="N3C Data Access" src="https://user-images.githubusercontent.com/59209633/84328360-9c794b80-ab36-11ea-9d09-96f4cd6a34bc.PNG">
.

**Comment by amvolz** [comment]
Adam Wilcox provided this great diagram.
[Data pre and Approval workflow - All components.pdf](https://github.com/National-COVID-Cohort-Collaborative/covid.cd2h.org/files/4761735/Data.pre.and.Approval.workflow.-.All.components.pdf)

**Comment by LisaOKeefe1** [comment]
HI @amvolz! Thanks for sharing the doc from Adam and team. It looks great. In what situations do we imagine sharing this? Emily and I are not quite clear on what, if any deliverables, you may need from us. Can you please help me understand better and we can go from there.  Thanks.

**Comment by amvolz** [comment]
@LisaOKeefe for this ticket in the Website Repository, this is information for the web team to use for the design of a new webpage. (If there is another process for sharing this, I imagine a ticket would be created in the Operations Repository, but I don't have information on that.) Thanks!

**Comment by amvolz** [comment]
Rich will integrate image from methods manuscript into his architecture (was vetted by many contributors). 
@monicacecilia will add the image to this ticket for Rich to access.

**Comment by monicacecilia** [comment]
![Fig2_N3C_Governance_2020-06-20f](https://user-images.githubusercontent.com/1714621/86272438-6eaa8400-bb83-11ea-9e0b-7d49d4a6086e.jpg)

**Comment by monicacecilia** [comment]
@richalorimor the PDF can be found [here](https://www.dropbox.com/sh/3w2n2o9iqvn0atb/AAAZF-nwVo2iyvOs5QNQviM9a?dl=0&preview=Fig2_N3C_Governance_2020-06-20f.pdf).

**Comment by amvolz** [comment]
This has been now addressed over 3 webpages: [Institution Essentials](https://covid.cd2h.org/Institution_Essentials), [Researcher Essentials](https://covid.cd2h.org/Researcher_Essentials), and [Access the N3C Data Enclave](https://covid.cd2h.org/N3C_data_enclave)
