### ISSUE TITLE
Add page about workstreams, subgroups, and task teams

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#41]
Workstreams comprise major endeavors in the N3C in a "pipe". We don't anticipate perhaps more than one more being added (Implementation)

Subgroups are major divisions of the workstream and are intended to be integrative within the workstream.

Task teams are ad hoc groups designed for a given task. They can span workstreams and subgroups. 

The page should include information about how to propose a new group of any of the three types. Note that Workstreams and subgroups must be approved by the Leads group. Task teams must be attached to at least one workstream for reporting out.

Workstreams and Subgroups have regular meetings and full PM support. All three types of groups have google docs and slack channels. Task teams are self organizing and may need to "visit" multiple workstreams and subgroups to get their task done. A good example is the hashing task team, which has both 'Phenotyping and Data Acquisition' issues as well as Governance and Data Partnership" issues.

**Comment by amvolz** [comment]
@mellybelly Rich is drafting a page to present this structural content. We will place a link/icon for it with the Onboarding Section on the landing page, as well as create a link for it on the top Navigation Bar-N3C Workstreams. Once page is created, I can craft the language accordingly.

**Comment by amvolz** [comment]
Rich will hand off the "shell" he designed to Alexis and Will this week. Andrea will work with Iowa team to populate content.
