### ISSUE TITLE
Change names of webinars & bulletins in the ABOUT menu

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#42]
Per @waldenan comments, she suggests name changes for 2 items under the ABOUT menu:
N3C Webinars → N3C Presentations
N3C Bulletins → N3C Updates

We discussed in web meeting that it will have no significant impact on SEO.
@mellybelly Do you have an opinion on renaming these items?

**Comment by amvolz** [comment]
More discussions with Anita who has given final approval. About menu items can be changed to:
N3C Presentations & Webinars
N3C Newsletters

@alexisgraves No further approval required, per Anita!

**Comment by alexisgraves** [comment]
Done :) 👍

**Comment by monicacecilia** [comment]
:bowtie:
