### ISSUE TITLE
Show leadership on homepage

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#44]
Right now there is only one quote from me. 
Some things that might be considered:

- alternate quotes in a banner
- leads names next to the workstream
- relationship to CD2H and its leadership

Not sure the best plan. Others should weigh in with ideas.

**Comment by amvolz** [comment]
@mellybelly Leadership is under the ABOUT menu under "Who We Are".  We are currently re-designing workstream pages, and leads and PMs will be pictured there. Does this address the title of this ticket and bullet 2?

**Comment by mellybelly** [comment]
partly ;-).

right now on the landing page, it is only me on the quote, which doesn't highlight other leadership, especially Ken and Chris. 
can we think of a way to have rotating quotes from our leaders?  or some other landing page acknowledgement, i'm not sure what will work. Or we could just take me off.  

Would be good to review the update plans too.
@cgchute may have some suggestions.

**Comment by amvolz** [comment]
@mellybelly Happy to discuss our update plans with you. Right now the workstream leads & PMs are reviewing their respective storyboard slides to give input on what they want on their new pages. https://docs.google.com/presentation/d/1YvS_Q-g0tzcm91oAK988UAaG3WlGJUsosj5lx7bxwIo/edit#slide=id.g52f7581435_0_0

**Comment by amvolz** [comment]
@mellybelly The place where your quote is on the N3C home page is a static field and I can easily swap it out or remove completely, whichever you want. Do you want me to replace it with John Buse's or Warren Kibbe's quotes that I already have?

**Comment by amvolz** [comment]
Replaced quote on home page.

**Comment by cgchute** [comment]
I like the new quote, presume it will rotate.  Thank you, Melissa, for being so egalitarian.

**Comment by amvolz** [comment]
@cgchute Can we get a quote from you as well? Thanks!

**Comment by amvolz** [comment]
@KenGersing When you have a chance, can you provide an N3C leadership quote for the website? Thank you!

**Comment by cgchute** [comment]
The N3C establishes the precedent for EHR data integration on a secure enclave to support clinical discovery enabled by collaborative, large-scale, computationally-intensive data science.

**Comment by amvolz** [comment]
- Leadership quotes are now rotating on the home page (Melissa's has been removed per her request); continued requests going out to obtain more quotes for display on home page.

- Leads names & headshots are ready to post on workstream pages. Redevelopment of workstream pages is a priority and currently in the works.

- Statement for "Relationship to CD2H and its Leadership" has been written by Andrea and placed on the Mission page under the ABOUT menu: "The onset of the COVID-19 pandemic has provided a unique opportunity to leverage CD2H resources and expertise already well-established within the informatics and medical communities. CD2H leaders have an integral role in creating the infrastructure of the N3C to synergize discoveries and meet the emerging needs brought to light by the novel coronavirus."
(This statement can go on the home page if preferred?)

**Comment by amvolz** [comment]
- Revised statement for the "Relationship to CD2H and its Leadership" with input by Chris Chute: "The onset of the COVID-19 pandemic has provided a unique opportunity to leverage CD2H resources and expertise already well-established within the informatics and medical communities. Most of the CD2H projects have been incorporated into the N3C: Text Analytics/Natural Language Processing is most active in N3C led by Hongfang Liu; Machine Learning is now applied to N3C on the Palantir platform led by Heidi Spratt and Peter Robinson; Data Quality has become entirely focused as a component of the harmonization pipeline in partnership with OHDSI, and as post-processing in the analytics environment. CD2H leaders have an integral role in creating the infrastructure of the N3C to synergize discoveries and meet the emerging needs brought to light by the novel coronavirus."

(Still on Mission page but can be moved out to home page if requested.)

**Comment by amvolz** [comment]
- Melissa's quote has been returned to the home page; added to the carousel along with rotating leadership quotes.
- Ken Gersing is working on providing a quote.
- Design decision to keep newly added "Relationship to CD2H" statement on Mission page, as not a good fit for home page.

I believe this ticket has been addressed?
