### ISSUE TITLE
ONBOARD Here need to be much bigger...create a button by July 8th

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#45]
On the homepage under "Become a Valued N3C Partner the Onboard information is kinda lost on this page but it is one of the most important items.  Will you make this a clickable button that opens the form  and make it much bigger on the button..."ONBOARD TO N3C".  You can show me a prototype.

Would like to have the prototype by Tuesday and implemented by Wed.

Thanks!

**Comment by alexisgraves** [comment]
The button has been approved and is now live on the website. :)

**Comment by amvolz** [comment]
Can we close this ticket?

**Comment by amvolz** [comment]
@alexisgraves: @waldenan and @cgcook have requested to ALSO make the onboarding link tittled "here" on the new onboarding instructions page into a purple rectangular button (like the others lower down on that page).  Thanks!

**Comment by cgcook** [comment]
@alexisgraves on the new onboarding instructions page, could we have the button read: "REGISTER HERE"  

We want to clarify that registration = completing the form; onboarding = requesting access to the drive and google groups. 

Thanks!

**Comment by alexisgraves** [comment]
Done! :) 
<img width="300" alt="Screen Shot 2020-07-08 at 2 08 07 PM" src="https://user-images.githubusercontent.com/12225601/86960069-96ba5a00-c124-11ea-9111-68f2358475dc.png">

**Comment by cgcook** [comment]
Awesome, thanks Alexis.  Thanks Andrea.  

Any ETA on when the updated instruction page will go live?

**Comment by amvolz** [comment]
@cgcook Updated instructions page is live.

**Comment by cgcook** [comment]
Awesome, thanks @amvolz and @alexisgraves!! Who wants the honor of closing this ticket?  :-)

**Comment by amvolz** [comment]
Hee hee. My favorite part :)
