### ISSUE TITLE
Governance web page- add grid - Due Thursday  July 9th

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#46]
We will reference this table in an upcoming article coming out this week. 

Will you add this to the Governance page.   Can you place it under the mission. Make it a little smaller. I would like to see a prototype.

Alexis I am assigning it to you but please pass off to another team member to help you. 
Tiers
https://drive.google.com/drive/folders/164RHF_NhEee_MZKZ8GSVmaNwgqXLQFN9

**Comment by amvolz** [comment]
Alexis is creating [test page](https://covid-test.cd2h.org/N3C_governance) to add tiers grid to Governance page. Now in final stages. Will be live by Fri 7/10 for release of Ansible article on N3C Governance Process.

**Comment by alexisgraves** [comment]
The table has been approved and is now live! :)
