### ISSUE TITLE
Domain Team SOP for launching on web page

### ISSUE THREAD

**Issue by andrewjneumann** [National-COVID-Cohort-Collaborative/covid.cd2h.org#47]
"how to launch an analytics task team"  instructions per @mellybelly 
current task team listing and join instructions - how to integrate existing teams into the website
SOP listed somewhere too :-) 
Current CA subgroup task teams [here](https://docs.google.com/spreadsheets/d/1t6QLrp-Fkg70xuKOask8nXOJmFcDkTVqEAKqFsFdKy4/edit#gid=1406556830)

**Comment by andrewjneumann** [comment]
Per web meeting, will integrate SOP & task team lists into existing google doc link. TBD on-page for 'how to launch' but discussed making it a sub-page of subgroups once we define that.

**Comment by amvolz** [comment]
New [Onboarding Instructions page](https://covid.cd2h.org/onboarding_instructions) is now live on website. There is a link under "Details for Workstreams" that goes to the Google doc where task teams can be listed and amended as often as needed, and will always display as current on the website.

**Comment by amvolz** [comment]
@andrewjneumann Has this been addressed now with the new Domain Team pages?

**Comment by amvolz** [comment]
@andrewjneumann Has this been addressed now with the new Domain Team pages?
