### ISSUE TITLE
Change title of Case Report Forms and Phenotyping Standards page

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#5]
This page: https://covid.cd2h.org/forms_and_standards
is currently titled: 
COVID Case Report Forms and Phenotyping Standards
I think perhaps it should be retitled to:
COVID Case Report Forms, Standards, and Protocols

Then, perhaps a reorg with links to protocol/pre-trial info at https://www.covidcp.org/ and the new CLIC/TIN pre-registration link when its live 
@eichmann what do you think?

**Comment by alexisgraves** [comment]
https://covid.cd2h.org/forms_and_standards has been renamed to "COVID Case Report Forms, Standards, and Protocols"

**Comment by monicacecilia** [comment]
Thank you! :bowtie:
