### ISSUE TITLE
Home page change- for Soft Launch -Add Researcher Page

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#51]
To prepare for the soft launch opening for the Enclave we need a way for researchers to access the Data from the N3C website
Update the Web home page to include a Research Box that leads to a Research page.(see[ link to slide [#2)](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g8bd6e3886b_6_46)

- [x] the first band on the home page should have access to the Research page and the onboarding
- [x] 2nd band Welcome Packet and NIH links

Takes you to a:
- [x] Research page: portal to Enclave for First time users and Returning users. See slide 3 [side 3](https://docs.google.com/presentation/d/14ZFzZJClSm_F-JLIsuE6vDPuBn6qxMVBvKwy76OR2bM/edit#slide=id.g8bd6e3886b_6_68)  
- [x] Need a section to write text to describe what an Enclave is 
- [x] Need a link to the Data Access Tiers to the Governance page

This is just for the launch. We will make modifications to add additional information CTSAs and Researchers will need or want.

@amvolz

**Comment by amvolz** [comment]
Definition from the [NIH National Library of Medicine](https://nnlm.gov/data/thesaurus/data-enclave), “A data enclave is a secure network through which confidential data, such as identifiable information from census data, can be stored and disseminated. In a virtual data enclave a researcher can access the data from their own computer but cannot download or remove it from the remote server. Higher security data can be accessed through a physical data enclave where a researcher is required to access the data from a monitored room where the data is stored on non-network computers.”

**Comment by waldenan** [comment]
Nice work on the Data Access page. You have included some good content and instructions. I like the big bold numbers.

For Launch this is fine and here is a [link](https://docs.google.com/document/d/1o8Em0hfF1M5O-9lMSQB8S_fDnTUfOfanmMAFbaqK5lg/edit) with minor wording modifications.  We want less on the page for now rather than symmetry.

Soon we will want links to additional research information.
