### ISSUE TITLE
N3C Institution Users who submitted DUR

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#52]
We need a place on the website where institution can go to review who has submitted a DUR through the N3C Enclave. 

the N3C website should have:

- [x] List of institutions and with their list of users, projects and access type.  (priority) **Date: August 14th by the time it is opened to other users beyond the soft launch** 
- [x] a mechanism to report issues...
a form to request modifications to user access (next phase)

**Comment by eichmann** [comment]
Currently waiting on data feed from Foundry.

**Comment by amvolz** [comment]
- Does the [DUA Signatory page ](https://covid.cd2h.org/enclave_DUA_signatories)address this ticket?
- The [Support Desk](https://covid.cd2h.org/help_desk) is the mechanism to report issues.

I believe this ticket can be closed.
