### ISSUE TITLE
Create webpages for Domain Teams

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#55]
We'd like to have the task teams have a template for deploying their activities with links to their google docs and meetings, as well as the listing of the DUR submitted projects associated with the task team.

**Comment by amvolz** [comment]
This is being drafted by @alexisgraves. Note name change to "Domain Teams"

**Comment by amvolz** [comment]
I have drafted 4 slides on the storyboard/wireframe to begin layout. @andrewjneumann is gathering descriptions from the domain leads. @alexisgraves has begun styling.

**Comment by amvolz** [comment]
Domain Page has been created. Approved by Anita and Andrew to go live. https://covid-dev.cd2h.org/Domain_Teams

**Comment by amvolz** [comment]
Pages have been created and are live. https://covid.cd2h.org/Domain_Teams (Minor details need to be added. See Issue 64.)
