### ISSUE TITLE
N3C Research Resources Page- Fact Sheet posting

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#56]
We want to post the weekly data release fact sheets on the Research Resources Web section. Here is a link to the previous Fact Sheet for your reference. I am working with Data Harm to determine where we can pick these up on a regular basis.

@mellybelly also mentioned wanting to post these to Zenodo but we should double check to see if that is still the plan

[Fact Sheet](https://docs.google.com/document/d/17TECU1y1JNDRjMdju1EeSyTsM8z8AyCAsaySIH-cPzc/edit)

**Comment by amvolz** [comment]
@waldenan See response in #59 which is a repeat of this issue.

**Comment by amvolz** [comment]
@jmcmurry Let us know when the Fact Sheet is posted on Zenodo so we can link to Researcher Essentials page to take care of this issue and #59 which are duplicates.

**Comment by amvolz** [comment]
Closing this duplicative ticket. See GitHub #59 to further this conversation.
