### ISSUE TITLE
Sunset Original and Create New Welcome Partnership Packet with Links to Official Places

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#57]
Decision to sunset the original Welcome Partnerhsip Packet from May 2020. Four of the documents are not current/compliant with NIH/NCATS. The other documents are now housed in more official resource locations (i.e. N3C website pages, NCATS N3C webpage, Zenodo).

A new document is being created as a "virtual parternship packet" with links to the official places based on some of the language from Ken Gersing's welcome email template. Icons and graphics can be added from the new NCATS Communications Guidance kit when it is released on Sept 1st.

In the meantime, the original packet on the website will be taken down with a note saying new content is coming soon.

**Comment by alexisgraves** [comment]
The partnership packet (and all individual chapter pages) has been hidden from the main menu and unpublished. The button to access it on the [onboarding instructions page](https://covid.cd2h.org/onboarding_instructions) has also temporarily been replaced with "New Packet Comming Soon" text. Please let me know if we need to worry about redirecting the old URLs to the locations of the new documents. :)

**Comment by amvolz** [comment]
All "packet" information now lives under the Institution Essentials or Researcher Essentials pages.
