### ISSUE TITLE
Create webpage to Highlight Tools in the Enclave

### ISSUE THREAD

**Issue by mellybelly** [National-COVID-Cohort-Collaborative/covid.cd2h.org#58]
It would be great to have a public page for some of the more interesting/community developed tools in the Enclave.

Thinking about Translator tools, KG-COVID-19, ATLAS/OHDSI tools, etc.

@newgene @eichmann

**Comment by andrewjneumann** [comment]
@aew0330

**Comment by amvolz** [comment]
We have discussed this at website workgroups. Liz Zampino is working on a storyboard/wireframe slide. She will have a draft this week or next. Alexis will working on styling.

**Comment by amvolz** [comment]
Liz Z created Tools storyboard slide. Discussing 10/7/2020.

**Comment by amvolz** [comment]
Alexis has created a test webpage here: https://covid.cd2h.org/node/385 

OMOP tools: Atlas is not yet in Foundry but discussions about porting it into Foundry (will be awhile)
R VS Python: why, difference, what can you do, training? Etc.

**Comment by amvolz** [comment]
[Enclave Tools page](https://covid.cd2h.org/Enclave_Tools) is now live. The search function still has to be developed by Dave. Needs to get logs to concentrate curation effort on high value tools. This is on Dave's list of widgets to build.
