### ISSUE TITLE
Add Fact Sheet to the Research Resource Page 

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#59]
Add Fact Sheet to the Research Essential Page 

We need a link to the Fact sheet. This can be temporary until Dave is able to create a Dashboard to display the weekly numbers.

It can be linked to a DOI. @jmcmurry can add the Fact Sheet to Zenodo

**Comment by amvolz** [comment]
@jmcmurry Let me know when you have had a chance to put the Fact Sheet in Zenodo, and I will link to the Researcher Essentials page. Thanks!

**Comment by DaveraGabriel** [comment]
please also see this requirements document dated 28Sept20  in addition to the fact sheets, there are additional reporting information we need from inside the enclave.  If there is going to be exporting information out, it should come from the same channel.
https://docs.google.com/document/d/1mc8Qa8-F7wtEXvCLM91DmkhXKuvwnLg8pLheCIyKjzQ/edit

**Comment by amvolz** [comment]
Combining comment from GitHub #56 opened on Aug 20 so we don't have duplicative tickets and can close #56:

We want to post the weekly data release fact sheets on the Research Resources Web section. Here is a link to the previous Fact Sheet for your reference. I am working with Data Harm to determine where we can pick these up on a regular basis.

@mellybelly also mentioned wanting to post these to Zenodo but we should double check to see if that is still the plan

@jmcmurry Let us know when the Fact Sheet is posted on Zenodo so we can link to Researcher Essentials page to take care of this issue and #59 which are duplicates.

**Comment by amvolz** [comment]
Fact sheet has been posted under the ABOUT as of 11/10/2020. (https://covid.cd2h.org/fact-sheet)
This is a temporary fix and will have to updated manually on  weekly basis.

@jmcmurry Let us know when the Fact Sheet is posted on Zenodo so we can link it instead. Thank you!

**Comment by amvolz** [comment]
This is done! [Fact Sheet page](https://covid.cd2h.org/fact-sheet) currently being manually updated, but soon to be automated.
