### ISSUE TITLE
Domain Teams web page - place on CLIC and TIN/List of members or roles

### ISSUE THREAD

**Issue by waldenan** [National-COVID-Cohort-Collaborative/covid.cd2h.org#61]
- [x] Create a widget to embed the Domain Team Web page on the CLIC and TIN websites

- [x] Organizations want to see a list of members, their organization and roles for domains teams accessed on the web page. This is to identify which organization is not represented on the domain teams @andrewjneumann

**Comment by amvolz** [comment]
Will provide CLIC & TIN with new Domain Team Webpage https://covid-dev.cd2h.org/Domain_Teams

**Comment by amvolz** [comment]
Will provide CLIC & TIN with new Domain Team webpage now live on production site: https://covid.cd2h.org/Domain_Teams
Dave to provide widget.

**Comment by eichmann** [comment]
We now have a framework in place to shadow the Drupal project model (workstreams, subgroups, domain teams, and relevant bios) in a Labs database schema. This is refreshed every 4 hours. JSON widget with domain team (and leads) info is operational at https://labs.cd2h.org/n3c_dashboard/embedded_domain_team_roster.jsp

**Comment by amvolz** [comment]
Thank you @eichmann! I will send the link to Robert White at CLIC. I will also provide the link to Terri Edwards & Julia Dunagan of TIN after we meet with them on Nov 5th.

**Comment by amvolz** [comment]
Per Robert White: CLIC is "freshening up" the CLIC website and will be incorporating a new N3C page where I believe this widget will live. This isn't expected to go live until November sometime.

**Comment by eichmann** [comment]
We ( @alexisgraves ) have sample scripting to consume widget data and paint it nicely on a Drupal page, should they have a need for it.

**Comment by amvolz** [comment]
JSON file widget was sent to both Robert White at CLIC and Julia Dunagan at TIN to embed on their websites. We are waiting to hear if they were successful. Or maybe need html file?

**Comment by amvolz** [comment]
TIN was not able to embed the widget, but did put a link to our Domain Team page in the [TIN Toolbox](https://trialinnovationnetwork.org/recruitment-retention-toolkit/).

CLIC had problems with the widget too. Checking with Robert White to see if they can also link to our webpage on their Resources page.

**Comment by amvolz** [comment]
N3C Domain Team pages now have the web link accessible from both the [Center for Leading Innovation & Collaboration (CLIC) Resource & Tool Center](https://clic-ctsa.org/resource-tool-center) and the [Trial Innovation Network (TIN) website toolkit.](https://trialinnovationnetwork.org/recruitment-retention-toolkit/) 

The widget was not able to be used, but mission accomplished.
