### ISSUE TITLE
Link to DTA Signatory List from NCATS N3C web page

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#63]

**Comment by amvolz** [comment]
On website workgroup meeting agenda for 9/30. Will discuss with @eichmann and @alexisgraves.

**Comment by amvolz** [comment]
On hold while NCATS checks on logistics of this.

**Comment by amvolz** [comment]
Per Governance meeting 10/6/2020, DTA list will be posted on NCATS N3C web page. N3C website will link to it. Waiting for link to be created.

**Comment by amvolz** [comment]
@alexisgraves NCATS has now created [DTA Signatory list page](https://ncats.nih.gov/n3c/resources/data-contribution/data-transfer-agreement-signatories) and is ready to link on N3C site.

This ticket can be closed once it is up on the N3C site.

**Comment by alexisgraves** [comment]
The DTA Signatories Link is now up on the menu under N3C Data Enclave :)  

<img width="308" alt="Screen Shot 2020-10-22 at 12 53 36 PM" src="https://user-images.githubusercontent.com/12225601/96910863-b2443900-1465-11eb-8fa6-72ba642ca77c.png">
