### ISSUE TITLE
Updates to domain team landing page/domain team main page(s)

### ISSUE THREAD

**Issue by andrewjneumann** [National-COVID-Cohort-Collaborative/covid.cd2h.org#64]
https://covid.cd2h.org/Domain_Teams

- [x] Change Lavance's company to Cellgen Technologies
- [x] Add elder impact co-lead Jessica Islam (headshot in drive folder)
- [x] CCM/MODS (critical care) replace Tell with Vignesh Subbian
- [x] Change picture for Hemalkumar Mehta (at https://covid.cd2h.org/node/368) (new in drive)
- [x] Add Imaging to cross-cutting
- [x] Rename "Calendar" to Domain Team meetings calendar

**Comment by amvolz** [comment]
@alexisgraves Can you please create tags for Jessica and Vignesh above so I can add them to their respective Domain Teams?  Their headshots are in the master headshot folder in the website folder. Thanks!

Imaging will be re-published once we receive their description.

**Comment by alexisgraves** [comment]
Bios for Jessica and Vignesh have been created and added to their respective domain teams :).

**Comment by amvolz** [comment]
Thank you @alexisgraves! We also have enough content to be able to publish the Elder Impact & Shot/Longterm Complications now. Thanks!

**Comment by amvolz** [comment]
Correction: Elder Impact already published. I meant Pediatrics. :)

**Comment by alexisgraves** [comment]
Pediatrics & Short/Longterm Complications are now up!

**Comment by amvolz** [comment]
@andrewjneumann If they choose to use Slack, we need channels for: 
AKI,
Critical Care/MODS,
Emergency Services
Short & Long-term Complications
ADMS, Imaging
Pharma-Commercial

**Comment by alexisgraves** [comment]
> If they choose to use Slack, we need channels for:
> AKI,
> Critical Care/MODS,
> Emergency Services
> Short & Long-term Complications
> ADMS, Imaging
> Pharma-Commercial

-- Slack links have now been added to every published domain team :) (Imaging can be published once we get the description)

**Comment by amvolz** [comment]
Thank you for supplying the Slack channels @andrewjneumann and thanks for posting @alexisgraves !
