### ISSUE TITLE
institution_id often missing from registration feed

### ISSUE THREAD

**Issue by jmcmurry** [National-COVID-Cohort-Collaborative/covid.cd2h.org#66]
The following email domains have no corresponding institution_id in the feed from registration form:

- nih.gov
- autoimmuneregistry.org
- orangewiresystems.com
- njhealth.org
- umn.edu
- iqvia.com
- ouhsc.edu
- theverge.com
- nemours.org
- rbhs.rutgers.edu
- sjsu.edu
- isbscience.org
- buffalo.edu
- princeton.edu
- ornl.gov
- syntegra.io
- mmm.com

My previous mapping of the domains to the ROR remains [here](https://docs.google.com/spreadsheets/d/12PlksXu_-JLQi_FtOqfpw6ioFwtUyfgTiaFHOFtrfx8/edit#gid=1377832078), but there may be some reason they're not yet in the feed.

@eichmann please advise, thanks

**Comment by amvolz** [comment]
@eichmann Is this an Enclave issue, not website?

**Comment by amvolz** [comment]
@jmcmurry Is this still an issue? How can the website team help?

**Comment by amvolz** [comment]
@jmcmurry we are closing things down here and converting to Jira. I don't understand what the ask is for the web team. Can I close this issue? Please let me know!

**Comment by amvolz** [comment]
No responses were ever given after several attempts. Moved information to the Jira N3CWEB-10 open ticket which seems to pertain to this issue. Closing this one out now.
