### ISSUE TITLE
Add details about webinars and other events

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#7]
A public N3C Google calendar has been created and is being populated with the workstream meetings, webinars, etc. Alexis will link to covid site.

**Comment by monicacecilia** [comment]
From @mellybelly: 
- I think [the website] should also list any upcoming events. E.g., I really want to be able to point people to the collaborative analytics meeting happening on Monday, but that is not posted anywhere public yet.

From @amvolz on #3 
- Create a menu item for webinars

**Comment by monicacecilia** [comment]
ToDo: 
- [ ] Moni to add Alexis to N3C GH org.

**Comment by amvolz** [comment]
These were 2 different issues.

1.       The upcoming events Melissa was referring to are a calendar that we ill possibly link to a Google calendar, or create one on the site for all meetings

2.       The place to store the webinars was meant to be an archived library of past webinars. This need to be reinstated. Sorry it was not clear.

Andrea

**Comment by amvolz** [comment]
Specifically, we need to create a place for archived webinars under the Curated Resources menu. We have them accumulating every week and no place to upload them. This is a separate issue from events, but can be addressed in this now combined ticket..

**Comment by monicacecilia** [comment]
Dear @amvolz, 

Indeed these were filed as different issues, but as described in the actions requested in the title,  they can be solved with a single task. I definitely did not pick up a request to "_create an archive of all webinars and make a library available through a menu item on the website_" from the description on the other ticket. :bowtie: And to make matters more confusing, the follow up comment on that ticket requests a "list all upcoming events." I hope you see my confusion, hehe. 

Those are indeed two different things. I'll open a new ticket with these updated instructions to avoid said confusion.  Thank you! :bowtie:

**Comment by monicacecilia** [comment]
@amvolz - I created a new ticket with request for archive and link for webinars. See #12.

**Comment by alexisgraves** [comment]
The [calendar](https://covid.cd2h.org/N3C_calendar) and [upcomming events](https://covid.cd2h.org/N3C) (on the bottom of the page) are on the N3C site, but we may want to restructure these as we make adjustments to the home page.

**Comment by monicacecilia** [comment]
@alexisgraves - Brilliant. Thanks Alexis! Yes, you are correct about wanting to restructure as we evolve the look and feel. For the time being, this action item is complete. I'll close here. :bowtie:
