### ISSUE TITLE
Add 4 New Domain Teams to Webpage

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#70]
Andrew is getting a lot of people asking about starting Domain Teams that are waiting be put up. Temporary placeholder suggestion to create 4 new Clinical Domain Teams tiles: Neurology/Stroke, Cardiology, Genomics, HPO/OMOP with this standard template:  _"The ______  Clinical Domain Team will explore issues related to ____ and COVID-19. More details on specific goals and leadership coming soon."_ Can use temporary avatars for lead headshots. 

Googlegroups, listservs, and join links are on this spreadsheet.  https://docs.google.com/spreadsheets/d/1t6QLrp-Fkg70xuKOask8nXOJmFcDkTVqEAKqFsFdKy4/edit#gid=1406556830

**Comment by amvolz** [comment]
**Correction:**
Neurology/Stroke & Cardiology = clinical
Genomics & HPO/OMOP = cross-cutting

**Comment by alexisgraves** [comment]
3 of the 4 new domain teams have been added, but we will need more information for all of them (see below). Once I have the Google Group information for Neurology/Stroke I should be able to start the page for it. 
| Domain Team      | Added | Missing                         | Cross-Cutting | URL                             |
|------------------|-------|---------------------------------|---------------|---------------------------------|
| Cardiology       | X     | Slack, Leads, full description             |               | https://covid.cd2h.org/node/438 |
| Genomics         | X     | Slack, leads, full description              | X             | https://covid.cd2h.org/node/439 |
| HPO-OMOP         | X     | Slack, Verify Leads Complete, full description | X             | https://covid.cd2h.org/node/440 |
| Neurology/Stroke |       | Google group Information , Slack, Leads, full description       |               |                                 |


@andrewjneumann & @amvolz please let me know next steps. Thank you!

**Comment by amvolz** [comment]
@andrewjneumann Let me know when there is more information, headshots, etc. to put on their pages. Neurology/Stroke can't go up at all until groups, listservs, join links are created. Thank you.

**Comment by amvolz** [comment]
The 4th new DT will be just Neurology. Here are the links needed to put up their page: n3c-dt-neurology@googlegroups.com, https://groups.google.com/g/n3c-dt-neurology. They don't have Slack channel yet, but Andrew says to use n3c-analytics for now.  Use the generic description like we did for the other 3 new ones. Andrew is working on getting real content for all 4 very soon!

**Comment by alexisgraves** [comment]
Neurology is now up :).  Current Status: 
 
| Domain Team      | Added | Missing                         | Cross-Cutting | URL                             |
|------------------|-------|---------------------------------|---------------|---------------------------------|
| Cardiology       | X     | Slack, Leads, full description             |               | https://covid.cd2h.org/cardiology |
| Genomics         | X     | Slack, leads, full description              | X             | https://covid.cd2h.org/genomics |
| HPO-OMOP         | X     | Slack, Verify Leads Complete, full description | X             | https://covid.cd2h.org/ontology |
| Neurology |X       |  Slack, Leads, full description       |               |https://covid.cd2h.org/neurology                              |

**Comment by amvolz** [comment]
All 4 are up. Detailed descriptions and leader headshots will be added when Andrew can provide. Closing this ticket. Can reopen in Jira if needed.
