### ISSUE TITLE
Messaging: only state what has been approved by NCATS

### ISSUE THREAD

**Issue by amvolz** [National-COVID-Cohort-Collaborative/covid.cd2h.org#9]
Do not list aspirational ideas or content

**Comment by monicacecilia** [comment]
Is there a concrete action item here? Else, we should add this to the ReadMe, or to a document about 'best practices' - or something of the like.

**Comment by amvolz** [comment]
No, not specifically. Agreed.

**Comment by monicacecilia** [comment]
Added this comment to [README](https://github.com/National-COVID-Cohort-Collaborative/covid.cd2h.org/blob/master/README.md) file.
